// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package tokenstore

import (
	"reflect"
	"strings"

	di "github.com/fluffy-bunny/sarulabsdi"
	"github.com/rs/zerolog/log"
)

// ReflectTypeIReferenceTokenStore used when your service claims to implement IReferenceTokenStore
var ReflectTypeIReferenceTokenStore = di.GetInterfaceReflectType((*IReferenceTokenStore)(nil))

// AddSingletonIReferenceTokenStore adds a type that implements IReferenceTokenStore
func AddSingletonIReferenceTokenStore(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("SINGLETON", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		})
	di.AddSingleton(builder, implType, implementedTypes...)
}

// AddSingletonIReferenceTokenStoreWithMetadata adds a type that implements IReferenceTokenStore
func AddSingletonIReferenceTokenStoreWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("SINGLETON", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logIReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})
	di.AddSingletonWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddSingletonIReferenceTokenStoreByObj adds a prebuilt obj
func AddSingletonIReferenceTokenStoreByObj(builder *di.Builder, obj interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("SINGLETON", reflect.TypeOf(obj), _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "obj",
		})
	di.AddSingletonWithImplementedTypesByObj(builder, obj, implementedTypes...)
}

// AddSingletonIReferenceTokenStoreByObjWithMetadata adds a prebuilt obj
func AddSingletonIReferenceTokenStoreByObjWithMetadata(builder *di.Builder, obj interface{}, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("SINGLETON", reflect.TypeOf(obj), _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "obj",
		},
		_logIReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddSingletonWithImplementedTypesByObjWithMetadata(builder, obj, metaData, implementedTypes...)
}

// AddSingletonIReferenceTokenStoreByFunc adds a type by a custom func
func AddSingletonIReferenceTokenStoreByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("SINGLETON", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		})
	di.AddSingletonWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddSingletonIReferenceTokenStoreByFuncWithMetadata adds a type by a custom func
func AddSingletonIReferenceTokenStoreByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("SINGLETON", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logIReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddSingletonWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// AddTransientIReferenceTokenStore adds a type that implements IReferenceTokenStore
func AddTransientIReferenceTokenStore(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("TRANSIENT", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		})

	di.AddTransientWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddTransientIReferenceTokenStoreWithMetadata adds a type that implements IReferenceTokenStore
func AddTransientIReferenceTokenStoreWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("TRANSIENT", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logIReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddTransientWithImplementedTypesWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddTransientIReferenceTokenStoreByFunc adds a type by a custom func
func AddTransientIReferenceTokenStoreByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("TRANSIENT", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		})

	di.AddTransientWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddTransientIReferenceTokenStoreByFuncWithMetadata adds a type by a custom func
func AddTransientIReferenceTokenStoreByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("TRANSIENT", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logIReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddTransientWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// AddScopedIReferenceTokenStore adds a type that implements IReferenceTokenStore
func AddScopedIReferenceTokenStore(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("SCOPED", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		})
	di.AddScopedWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddScopedIReferenceTokenStoreWithMetadata adds a type that implements IReferenceTokenStore
func AddScopedIReferenceTokenStoreWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("SCOPED", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logIReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})
	di.AddScopedWithImplementedTypesWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddScopedIReferenceTokenStoreByFunc adds a type by a custom func
func AddScopedIReferenceTokenStoreByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("SCOPED", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		})
	di.AddScopedWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddScopedIReferenceTokenStoreByFuncWithMetadata adds a type by a custom func
func AddScopedIReferenceTokenStoreByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIReferenceTokenStore)
	_logAddIReferenceTokenStore("SCOPED", implType, _getImplementedIReferenceTokenStoreNames(implementedTypes...),
		_logIReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logIReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddScopedWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// RemoveAllIReferenceTokenStore removes all IReferenceTokenStore from the DI
func RemoveAllIReferenceTokenStore(builder *di.Builder) {
	builder.RemoveAllByType(ReflectTypeIReferenceTokenStore)
}

// GetIReferenceTokenStoreFromContainer alternative to SafeGetIReferenceTokenStoreFromContainer but panics of object is not present
func GetIReferenceTokenStoreFromContainer(ctn di.Container) IReferenceTokenStore {
	return ctn.GetByType(ReflectTypeIReferenceTokenStore).(IReferenceTokenStore)
}

// GetManyIReferenceTokenStoreFromContainer alternative to SafeGetManyIReferenceTokenStoreFromContainer but panics of object is not present
func GetManyIReferenceTokenStoreFromContainer(ctn di.Container) []IReferenceTokenStore {
	objs := ctn.GetManyByType(ReflectTypeIReferenceTokenStore)
	var results []IReferenceTokenStore
	for _, obj := range objs {
		results = append(results, obj.(IReferenceTokenStore))
	}
	return results
}

// SafeGetIReferenceTokenStoreFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetIReferenceTokenStoreFromContainer(ctn di.Container) (IReferenceTokenStore, error) {
	obj, err := ctn.SafeGetByType(ReflectTypeIReferenceTokenStore)
	if err != nil {
		return nil, err
	}
	return obj.(IReferenceTokenStore), nil
}

// GetIReferenceTokenStoreDefinition returns that last definition registered that this container can provide
func GetIReferenceTokenStoreDefinition(ctn di.Container) *di.Def {
	def := ctn.GetDefinitionByType(ReflectTypeIReferenceTokenStore)
	return def
}

// GetIReferenceTokenStoreDefinitions returns all definitions that this container can provide
func GetIReferenceTokenStoreDefinitions(ctn di.Container) []*di.Def {
	defs := ctn.GetDefinitionsByType(ReflectTypeIReferenceTokenStore)
	return defs
}

// SafeGetManyIReferenceTokenStoreFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetManyIReferenceTokenStoreFromContainer(ctn di.Container) ([]IReferenceTokenStore, error) {
	objs, err := ctn.SafeGetManyByType(ReflectTypeIReferenceTokenStore)
	if err != nil {
		return nil, err
	}
	var results []IReferenceTokenStore
	for _, obj := range objs {
		results = append(results, obj.(IReferenceTokenStore))
	}
	return results, nil
}

type _logIReferenceTokenStoreExtra struct {
	Name  string
	Value interface{}
}

func _logAddIReferenceTokenStore(scopeType string, implType reflect.Type, interfaces string, extra ..._logIReferenceTokenStoreExtra) {
	infoEvent := log.Info().
		Str("DI", scopeType).
		Str("DI-I", interfaces).
		Str("DI-B", implType.Elem().String())

	for _, extra := range extra {
		infoEvent = infoEvent.Interface(extra.Name, extra.Value)
	}

	infoEvent.Send()

}
func _getImplementedIReferenceTokenStoreNames(implementedTypes ...reflect.Type) string {
	builder := strings.Builder{}
	for idx, implementedType := range implementedTypes {
		builder.WriteString(implementedType.Name())
		if idx < len(implementedTypes)-1 {
			builder.WriteString(", ")
		}
	}
	return builder.String()
}

// ReflectTypeIInternalReferenceTokenStore used when your service claims to implement IInternalReferenceTokenStore
var ReflectTypeIInternalReferenceTokenStore = di.GetInterfaceReflectType((*IInternalReferenceTokenStore)(nil))

// AddSingletonIInternalReferenceTokenStore adds a type that implements IInternalReferenceTokenStore
func AddSingletonIInternalReferenceTokenStore(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("SINGLETON", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		})
	di.AddSingleton(builder, implType, implementedTypes...)
}

// AddSingletonIInternalReferenceTokenStoreWithMetadata adds a type that implements IInternalReferenceTokenStore
func AddSingletonIInternalReferenceTokenStoreWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("SINGLETON", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})
	di.AddSingletonWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddSingletonIInternalReferenceTokenStoreByObj adds a prebuilt obj
func AddSingletonIInternalReferenceTokenStoreByObj(builder *di.Builder, obj interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("SINGLETON", reflect.TypeOf(obj), _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "obj",
		})
	di.AddSingletonWithImplementedTypesByObj(builder, obj, implementedTypes...)
}

// AddSingletonIInternalReferenceTokenStoreByObjWithMetadata adds a prebuilt obj
func AddSingletonIInternalReferenceTokenStoreByObjWithMetadata(builder *di.Builder, obj interface{}, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("SINGLETON", reflect.TypeOf(obj), _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "obj",
		},
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddSingletonWithImplementedTypesByObjWithMetadata(builder, obj, metaData, implementedTypes...)
}

// AddSingletonIInternalReferenceTokenStoreByFunc adds a type by a custom func
func AddSingletonIInternalReferenceTokenStoreByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("SINGLETON", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		})
	di.AddSingletonWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddSingletonIInternalReferenceTokenStoreByFuncWithMetadata adds a type by a custom func
func AddSingletonIInternalReferenceTokenStoreByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("SINGLETON", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddSingletonWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// AddTransientIInternalReferenceTokenStore adds a type that implements IInternalReferenceTokenStore
func AddTransientIInternalReferenceTokenStore(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("TRANSIENT", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		})

	di.AddTransientWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddTransientIInternalReferenceTokenStoreWithMetadata adds a type that implements IInternalReferenceTokenStore
func AddTransientIInternalReferenceTokenStoreWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("TRANSIENT", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddTransientWithImplementedTypesWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddTransientIInternalReferenceTokenStoreByFunc adds a type by a custom func
func AddTransientIInternalReferenceTokenStoreByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("TRANSIENT", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		})

	di.AddTransientWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddTransientIInternalReferenceTokenStoreByFuncWithMetadata adds a type by a custom func
func AddTransientIInternalReferenceTokenStoreByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("TRANSIENT", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddTransientWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// AddScopedIInternalReferenceTokenStore adds a type that implements IInternalReferenceTokenStore
func AddScopedIInternalReferenceTokenStore(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("SCOPED", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		})
	di.AddScopedWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddScopedIInternalReferenceTokenStoreWithMetadata adds a type that implements IInternalReferenceTokenStore
func AddScopedIInternalReferenceTokenStoreWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("SCOPED", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})
	di.AddScopedWithImplementedTypesWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddScopedIInternalReferenceTokenStoreByFunc adds a type by a custom func
func AddScopedIInternalReferenceTokenStoreByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("SCOPED", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		})
	di.AddScopedWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddScopedIInternalReferenceTokenStoreByFuncWithMetadata adds a type by a custom func
func AddScopedIInternalReferenceTokenStoreByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeIInternalReferenceTokenStore)
	_logAddIInternalReferenceTokenStore("SCOPED", implType, _getImplementedIInternalReferenceTokenStoreNames(implementedTypes...),
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logIInternalReferenceTokenStoreExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddScopedWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// RemoveAllIInternalReferenceTokenStore removes all IInternalReferenceTokenStore from the DI
func RemoveAllIInternalReferenceTokenStore(builder *di.Builder) {
	builder.RemoveAllByType(ReflectTypeIInternalReferenceTokenStore)
}

// GetIInternalReferenceTokenStoreFromContainer alternative to SafeGetIInternalReferenceTokenStoreFromContainer but panics of object is not present
func GetIInternalReferenceTokenStoreFromContainer(ctn di.Container) IInternalReferenceTokenStore {
	return ctn.GetByType(ReflectTypeIInternalReferenceTokenStore).(IInternalReferenceTokenStore)
}

// GetManyIInternalReferenceTokenStoreFromContainer alternative to SafeGetManyIInternalReferenceTokenStoreFromContainer but panics of object is not present
func GetManyIInternalReferenceTokenStoreFromContainer(ctn di.Container) []IInternalReferenceTokenStore {
	objs := ctn.GetManyByType(ReflectTypeIInternalReferenceTokenStore)
	var results []IInternalReferenceTokenStore
	for _, obj := range objs {
		results = append(results, obj.(IInternalReferenceTokenStore))
	}
	return results
}

// SafeGetIInternalReferenceTokenStoreFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetIInternalReferenceTokenStoreFromContainer(ctn di.Container) (IInternalReferenceTokenStore, error) {
	obj, err := ctn.SafeGetByType(ReflectTypeIInternalReferenceTokenStore)
	if err != nil {
		return nil, err
	}
	return obj.(IInternalReferenceTokenStore), nil
}

// GetIInternalReferenceTokenStoreDefinition returns that last definition registered that this container can provide
func GetIInternalReferenceTokenStoreDefinition(ctn di.Container) *di.Def {
	def := ctn.GetDefinitionByType(ReflectTypeIInternalReferenceTokenStore)
	return def
}

// GetIInternalReferenceTokenStoreDefinitions returns all definitions that this container can provide
func GetIInternalReferenceTokenStoreDefinitions(ctn di.Container) []*di.Def {
	defs := ctn.GetDefinitionsByType(ReflectTypeIInternalReferenceTokenStore)
	return defs
}

// SafeGetManyIInternalReferenceTokenStoreFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetManyIInternalReferenceTokenStoreFromContainer(ctn di.Container) ([]IInternalReferenceTokenStore, error) {
	objs, err := ctn.SafeGetManyByType(ReflectTypeIInternalReferenceTokenStore)
	if err != nil {
		return nil, err
	}
	var results []IInternalReferenceTokenStore
	for _, obj := range objs {
		results = append(results, obj.(IInternalReferenceTokenStore))
	}
	return results, nil
}

type _logIInternalReferenceTokenStoreExtra struct {
	Name  string
	Value interface{}
}

func _logAddIInternalReferenceTokenStore(scopeType string, implType reflect.Type, interfaces string, extra ..._logIInternalReferenceTokenStoreExtra) {
	infoEvent := log.Info().
		Str("DI", scopeType).
		Str("DI-I", interfaces).
		Str("DI-B", implType.Elem().String())

	for _, extra := range extra {
		infoEvent = infoEvent.Interface(extra.Name, extra.Value)
	}

	infoEvent.Send()

}
func _getImplementedIInternalReferenceTokenStoreNames(implementedTypes ...reflect.Type) string {
	builder := strings.Builder{}
	for idx, implementedType := range implementedTypes {
		builder.WriteString(implementedType.Name())
		if idx < len(implementedTypes)-1 {
			builder.WriteString(", ")
		}
	}
	return builder.String()
}
