// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package tasks

import (
	"reflect"
	"strings"

	di "github.com/fluffy-bunny/sarulabsdi"
	"github.com/rs/zerolog/log"
)

// ReflectTypeISingletonTask used when your service claims to implement ISingletonTask
var ReflectTypeISingletonTask = di.GetInterfaceReflectType((*ISingletonTask)(nil))

// AddSingletonISingletonTask adds a type that implements ISingletonTask
func AddSingletonISingletonTask(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("SINGLETON", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "type",
		})
	di.AddSingleton(builder, implType, implementedTypes...)
}

// AddSingletonISingletonTaskWithMetadata adds a type that implements ISingletonTask
func AddSingletonISingletonTaskWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("SINGLETON", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logISingletonTaskExtra{
			Name:  "DI-M",
			Value: metaData,
		})
	di.AddSingletonWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddSingletonISingletonTaskByObj adds a prebuilt obj
func AddSingletonISingletonTaskByObj(builder *di.Builder, obj interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("SINGLETON", reflect.TypeOf(obj), _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "obj",
		})
	di.AddSingletonWithImplementedTypesByObj(builder, obj, implementedTypes...)
}

// AddSingletonISingletonTaskByObjWithMetadata adds a prebuilt obj
func AddSingletonISingletonTaskByObjWithMetadata(builder *di.Builder, obj interface{}, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("SINGLETON", reflect.TypeOf(obj), _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "obj",
		},
		_logISingletonTaskExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddSingletonWithImplementedTypesByObjWithMetadata(builder, obj, metaData, implementedTypes...)
}

// AddSingletonISingletonTaskByFunc adds a type by a custom func
func AddSingletonISingletonTaskByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("SINGLETON", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "func",
		})
	di.AddSingletonWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddSingletonISingletonTaskByFuncWithMetadata adds a type by a custom func
func AddSingletonISingletonTaskByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("SINGLETON", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logISingletonTaskExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddSingletonWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// AddTransientISingletonTask adds a type that implements ISingletonTask
func AddTransientISingletonTask(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("TRANSIENT", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "type",
		})

	di.AddTransientWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddTransientISingletonTaskWithMetadata adds a type that implements ISingletonTask
func AddTransientISingletonTaskWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("TRANSIENT", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logISingletonTaskExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddTransientWithImplementedTypesWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddTransientISingletonTaskByFunc adds a type by a custom func
func AddTransientISingletonTaskByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("TRANSIENT", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "func",
		})

	di.AddTransientWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddTransientISingletonTaskByFuncWithMetadata adds a type by a custom func
func AddTransientISingletonTaskByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("TRANSIENT", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logISingletonTaskExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddTransientWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// AddScopedISingletonTask adds a type that implements ISingletonTask
func AddScopedISingletonTask(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("SCOPED", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "type",
		})
	di.AddScopedWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddScopedISingletonTaskWithMetadata adds a type that implements ISingletonTask
func AddScopedISingletonTaskWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("SCOPED", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logISingletonTaskExtra{
			Name:  "DI-M",
			Value: metaData,
		})
	di.AddScopedWithImplementedTypesWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddScopedISingletonTaskByFunc adds a type by a custom func
func AddScopedISingletonTaskByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("SCOPED", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "func",
		})
	di.AddScopedWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddScopedISingletonTaskByFuncWithMetadata adds a type by a custom func
func AddScopedISingletonTaskByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeISingletonTask)
	_logAddISingletonTask("SCOPED", implType, _getImplementedISingletonTaskNames(implementedTypes...),
		_logISingletonTaskExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logISingletonTaskExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddScopedWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// RemoveAllISingletonTask removes all ISingletonTask from the DI
func RemoveAllISingletonTask(builder *di.Builder) {
	builder.RemoveAllByType(ReflectTypeISingletonTask)
}

// GetISingletonTaskFromContainer alternative to SafeGetISingletonTaskFromContainer but panics of object is not present
func GetISingletonTaskFromContainer(ctn di.Container) ISingletonTask {
	return ctn.GetByType(ReflectTypeISingletonTask).(ISingletonTask)
}

// GetManyISingletonTaskFromContainer alternative to SafeGetManyISingletonTaskFromContainer but panics of object is not present
func GetManyISingletonTaskFromContainer(ctn di.Container) []ISingletonTask {
	objs := ctn.GetManyByType(ReflectTypeISingletonTask)
	var results []ISingletonTask
	for _, obj := range objs {
		results = append(results, obj.(ISingletonTask))
	}
	return results
}

// SafeGetISingletonTaskFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetISingletonTaskFromContainer(ctn di.Container) (ISingletonTask, error) {
	obj, err := ctn.SafeGetByType(ReflectTypeISingletonTask)
	if err != nil {
		return nil, err
	}
	return obj.(ISingletonTask), nil
}

// GetISingletonTaskDefinition returns that last definition registered that this container can provide
func GetISingletonTaskDefinition(ctn di.Container) *di.Def {
	def := ctn.GetDefinitionByType(ReflectTypeISingletonTask)
	return def
}

// GetISingletonTaskDefinitions returns all definitions that this container can provide
func GetISingletonTaskDefinitions(ctn di.Container) []*di.Def {
	defs := ctn.GetDefinitionsByType(ReflectTypeISingletonTask)
	return defs
}

// SafeGetManyISingletonTaskFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetManyISingletonTaskFromContainer(ctn di.Container) ([]ISingletonTask, error) {
	objs, err := ctn.SafeGetManyByType(ReflectTypeISingletonTask)
	if err != nil {
		return nil, err
	}
	var results []ISingletonTask
	for _, obj := range objs {
		results = append(results, obj.(ISingletonTask))
	}
	return results, nil
}

type _logISingletonTaskExtra struct {
	Name  string
	Value interface{}
}

func _logAddISingletonTask(scopeType string, implType reflect.Type, interfaces string, extra ..._logISingletonTaskExtra) {
	infoEvent := log.Info().
		Str("DI", scopeType).
		Str("DI-I", interfaces).
		Str("DI-B", implType.Elem().String())

	for _, extra := range extra {
		infoEvent = infoEvent.Interface(extra.Name, extra.Value)
	}

	infoEvent.Send()

}
func _getImplementedISingletonTaskNames(implementedTypes ...reflect.Type) string {
	builder := strings.Builder{}
	for idx, implementedType := range implementedTypes {
		builder.WriteString(implementedType.Name())
		if idx < len(implementedTypes)-1 {
			builder.WriteString(", ")
		}
	}
	return builder.String()
}

// ReflectTypeITaskEngine used when your service claims to implement ITaskEngine
var ReflectTypeITaskEngine = di.GetInterfaceReflectType((*ITaskEngine)(nil))

// AddSingletonITaskEngine adds a type that implements ITaskEngine
func AddSingletonITaskEngine(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("SINGLETON", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "type",
		})
	di.AddSingleton(builder, implType, implementedTypes...)
}

// AddSingletonITaskEngineWithMetadata adds a type that implements ITaskEngine
func AddSingletonITaskEngineWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("SINGLETON", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logITaskEngineExtra{
			Name:  "DI-M",
			Value: metaData,
		})
	di.AddSingletonWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddSingletonITaskEngineByObj adds a prebuilt obj
func AddSingletonITaskEngineByObj(builder *di.Builder, obj interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("SINGLETON", reflect.TypeOf(obj), _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "obj",
		})
	di.AddSingletonWithImplementedTypesByObj(builder, obj, implementedTypes...)
}

// AddSingletonITaskEngineByObjWithMetadata adds a prebuilt obj
func AddSingletonITaskEngineByObjWithMetadata(builder *di.Builder, obj interface{}, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("SINGLETON", reflect.TypeOf(obj), _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "obj",
		},
		_logITaskEngineExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddSingletonWithImplementedTypesByObjWithMetadata(builder, obj, metaData, implementedTypes...)
}

// AddSingletonITaskEngineByFunc adds a type by a custom func
func AddSingletonITaskEngineByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("SINGLETON", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "func",
		})
	di.AddSingletonWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddSingletonITaskEngineByFuncWithMetadata adds a type by a custom func
func AddSingletonITaskEngineByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("SINGLETON", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logITaskEngineExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddSingletonWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// AddTransientITaskEngine adds a type that implements ITaskEngine
func AddTransientITaskEngine(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("TRANSIENT", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "type",
		})

	di.AddTransientWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddTransientITaskEngineWithMetadata adds a type that implements ITaskEngine
func AddTransientITaskEngineWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("TRANSIENT", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logITaskEngineExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddTransientWithImplementedTypesWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddTransientITaskEngineByFunc adds a type by a custom func
func AddTransientITaskEngineByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("TRANSIENT", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "func",
		})

	di.AddTransientWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddTransientITaskEngineByFuncWithMetadata adds a type by a custom func
func AddTransientITaskEngineByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("TRANSIENT", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logITaskEngineExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddTransientWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// AddScopedITaskEngine adds a type that implements ITaskEngine
func AddScopedITaskEngine(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("SCOPED", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "type",
		})
	di.AddScopedWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddScopedITaskEngineWithMetadata adds a type that implements ITaskEngine
func AddScopedITaskEngineWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("SCOPED", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logITaskEngineExtra{
			Name:  "DI-M",
			Value: metaData,
		})
	di.AddScopedWithImplementedTypesWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddScopedITaskEngineByFunc adds a type by a custom func
func AddScopedITaskEngineByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("SCOPED", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "func",
		})
	di.AddScopedWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddScopedITaskEngineByFuncWithMetadata adds a type by a custom func
func AddScopedITaskEngineByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskEngine)
	_logAddITaskEngine("SCOPED", implType, _getImplementedITaskEngineNames(implementedTypes...),
		_logITaskEngineExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logITaskEngineExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddScopedWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// RemoveAllITaskEngine removes all ITaskEngine from the DI
func RemoveAllITaskEngine(builder *di.Builder) {
	builder.RemoveAllByType(ReflectTypeITaskEngine)
}

// GetITaskEngineFromContainer alternative to SafeGetITaskEngineFromContainer but panics of object is not present
func GetITaskEngineFromContainer(ctn di.Container) ITaskEngine {
	return ctn.GetByType(ReflectTypeITaskEngine).(ITaskEngine)
}

// GetManyITaskEngineFromContainer alternative to SafeGetManyITaskEngineFromContainer but panics of object is not present
func GetManyITaskEngineFromContainer(ctn di.Container) []ITaskEngine {
	objs := ctn.GetManyByType(ReflectTypeITaskEngine)
	var results []ITaskEngine
	for _, obj := range objs {
		results = append(results, obj.(ITaskEngine))
	}
	return results
}

// SafeGetITaskEngineFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetITaskEngineFromContainer(ctn di.Container) (ITaskEngine, error) {
	obj, err := ctn.SafeGetByType(ReflectTypeITaskEngine)
	if err != nil {
		return nil, err
	}
	return obj.(ITaskEngine), nil
}

// GetITaskEngineDefinition returns that last definition registered that this container can provide
func GetITaskEngineDefinition(ctn di.Container) *di.Def {
	def := ctn.GetDefinitionByType(ReflectTypeITaskEngine)
	return def
}

// GetITaskEngineDefinitions returns all definitions that this container can provide
func GetITaskEngineDefinitions(ctn di.Container) []*di.Def {
	defs := ctn.GetDefinitionsByType(ReflectTypeITaskEngine)
	return defs
}

// SafeGetManyITaskEngineFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetManyITaskEngineFromContainer(ctn di.Container) ([]ITaskEngine, error) {
	objs, err := ctn.SafeGetManyByType(ReflectTypeITaskEngine)
	if err != nil {
		return nil, err
	}
	var results []ITaskEngine
	for _, obj := range objs {
		results = append(results, obj.(ITaskEngine))
	}
	return results, nil
}

type _logITaskEngineExtra struct {
	Name  string
	Value interface{}
}

func _logAddITaskEngine(scopeType string, implType reflect.Type, interfaces string, extra ..._logITaskEngineExtra) {
	infoEvent := log.Info().
		Str("DI", scopeType).
		Str("DI-I", interfaces).
		Str("DI-B", implType.Elem().String())

	for _, extra := range extra {
		infoEvent = infoEvent.Interface(extra.Name, extra.Value)
	}

	infoEvent.Send()

}
func _getImplementedITaskEngineNames(implementedTypes ...reflect.Type) string {
	builder := strings.Builder{}
	for idx, implementedType := range implementedTypes {
		builder.WriteString(implementedType.Name())
		if idx < len(implementedTypes)-1 {
			builder.WriteString(", ")
		}
	}
	return builder.String()
}

// ReflectTypeITaskClient used when your service claims to implement ITaskClient
var ReflectTypeITaskClient = di.GetInterfaceReflectType((*ITaskClient)(nil))

// AddSingletonITaskClient adds a type that implements ITaskClient
func AddSingletonITaskClient(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("SINGLETON", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "type",
		})
	di.AddSingleton(builder, implType, implementedTypes...)
}

// AddSingletonITaskClientWithMetadata adds a type that implements ITaskClient
func AddSingletonITaskClientWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("SINGLETON", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logITaskClientExtra{
			Name:  "DI-M",
			Value: metaData,
		})
	di.AddSingletonWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddSingletonITaskClientByObj adds a prebuilt obj
func AddSingletonITaskClientByObj(builder *di.Builder, obj interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("SINGLETON", reflect.TypeOf(obj), _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "obj",
		})
	di.AddSingletonWithImplementedTypesByObj(builder, obj, implementedTypes...)
}

// AddSingletonITaskClientByObjWithMetadata adds a prebuilt obj
func AddSingletonITaskClientByObjWithMetadata(builder *di.Builder, obj interface{}, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("SINGLETON", reflect.TypeOf(obj), _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "obj",
		},
		_logITaskClientExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddSingletonWithImplementedTypesByObjWithMetadata(builder, obj, metaData, implementedTypes...)
}

// AddSingletonITaskClientByFunc adds a type by a custom func
func AddSingletonITaskClientByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("SINGLETON", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "func",
		})
	di.AddSingletonWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddSingletonITaskClientByFuncWithMetadata adds a type by a custom func
func AddSingletonITaskClientByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("SINGLETON", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logITaskClientExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddSingletonWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// AddTransientITaskClient adds a type that implements ITaskClient
func AddTransientITaskClient(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("TRANSIENT", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "type",
		})

	di.AddTransientWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddTransientITaskClientWithMetadata adds a type that implements ITaskClient
func AddTransientITaskClientWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("TRANSIENT", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logITaskClientExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddTransientWithImplementedTypesWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddTransientITaskClientByFunc adds a type by a custom func
func AddTransientITaskClientByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("TRANSIENT", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "func",
		})

	di.AddTransientWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddTransientITaskClientByFuncWithMetadata adds a type by a custom func
func AddTransientITaskClientByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("TRANSIENT", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logITaskClientExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddTransientWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// AddScopedITaskClient adds a type that implements ITaskClient
func AddScopedITaskClient(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("SCOPED", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "type",
		})
	di.AddScopedWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddScopedITaskClientWithMetadata adds a type that implements ITaskClient
func AddScopedITaskClientWithMetadata(builder *di.Builder, implType reflect.Type, metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("SCOPED", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "type",
		},
		_logITaskClientExtra{
			Name:  "DI-M",
			Value: metaData,
		})
	di.AddScopedWithImplementedTypesWithMetadata(builder, implType, metaData, implementedTypes...)
}

// AddScopedITaskClientByFunc adds a type by a custom func
func AddScopedITaskClientByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("SCOPED", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "func",
		})
	di.AddScopedWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddScopedITaskClientByFuncWithMetadata adds a type by a custom func
func AddScopedITaskClientByFuncWithMetadata(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), metaData map[string]interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITaskClient)
	_logAddITaskClient("SCOPED", implType, _getImplementedITaskClientNames(implementedTypes...),
		_logITaskClientExtra{
			Name:  "DI-BY",
			Value: "func",
		},
		_logITaskClientExtra{
			Name:  "DI-M",
			Value: metaData,
		})

	di.AddScopedWithImplementedTypesByFuncWithMetadata(builder, implType, build, metaData, implementedTypes...)
}

// RemoveAllITaskClient removes all ITaskClient from the DI
func RemoveAllITaskClient(builder *di.Builder) {
	builder.RemoveAllByType(ReflectTypeITaskClient)
}

// GetITaskClientFromContainer alternative to SafeGetITaskClientFromContainer but panics of object is not present
func GetITaskClientFromContainer(ctn di.Container) ITaskClient {
	return ctn.GetByType(ReflectTypeITaskClient).(ITaskClient)
}

// GetManyITaskClientFromContainer alternative to SafeGetManyITaskClientFromContainer but panics of object is not present
func GetManyITaskClientFromContainer(ctn di.Container) []ITaskClient {
	objs := ctn.GetManyByType(ReflectTypeITaskClient)
	var results []ITaskClient
	for _, obj := range objs {
		results = append(results, obj.(ITaskClient))
	}
	return results
}

// SafeGetITaskClientFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetITaskClientFromContainer(ctn di.Container) (ITaskClient, error) {
	obj, err := ctn.SafeGetByType(ReflectTypeITaskClient)
	if err != nil {
		return nil, err
	}
	return obj.(ITaskClient), nil
}

// GetITaskClientDefinition returns that last definition registered that this container can provide
func GetITaskClientDefinition(ctn di.Container) *di.Def {
	def := ctn.GetDefinitionByType(ReflectTypeITaskClient)
	return def
}

// GetITaskClientDefinitions returns all definitions that this container can provide
func GetITaskClientDefinitions(ctn di.Container) []*di.Def {
	defs := ctn.GetDefinitionsByType(ReflectTypeITaskClient)
	return defs
}

// SafeGetManyITaskClientFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetManyITaskClientFromContainer(ctn di.Container) ([]ITaskClient, error) {
	objs, err := ctn.SafeGetManyByType(ReflectTypeITaskClient)
	if err != nil {
		return nil, err
	}
	var results []ITaskClient
	for _, obj := range objs {
		results = append(results, obj.(ITaskClient))
	}
	return results, nil
}

type _logITaskClientExtra struct {
	Name  string
	Value interface{}
}

func _logAddITaskClient(scopeType string, implType reflect.Type, interfaces string, extra ..._logITaskClientExtra) {
	infoEvent := log.Info().
		Str("DI", scopeType).
		Str("DI-I", interfaces).
		Str("DI-B", implType.Elem().String())

	for _, extra := range extra {
		infoEvent = infoEvent.Interface(extra.Name, extra.Value)
	}

	infoEvent.Send()

}
func _getImplementedITaskClientNames(implementedTypes ...reflect.Type) string {
	builder := strings.Builder{}
	for idx, implementedType := range implementedTypes {
		builder.WriteString(implementedType.Name())
		if idx < len(implementedTypes)-1 {
			builder.WriteString(", ")
		}
	}
	return builder.String()
}
